server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NaoufalElAlaouiLamrani/micro-service
          clone-on-start: true
          default-label: main

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
