server:
  port: 8888 # Le port par défaut pour le Spring Cloud Config Server

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NaoufalElAlaouiLamrani/config-service
          search-paths: src/main/resources
          # L'URL de votre dépôt GitHub
          clone-on-start: true
          default-label: main # Branche principale de votre dépôt GitHub

logging:
  level:
    org.springframework.cloud.config.server: DEBUG # Activez les logs pour le debug si nécessaire
